#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

schedules:
# Cron timezone is UTC.
- cron: "0 18 * * *"
  displayName: Run tests daily at 6 PM UTC (11 AM PT)
  branches:
    include:
    - main
  always: true

# Do not run in PR builds nor support other triggers.
pr: none
trigger: none

variables:
- name: _TeamName
  value: AspNetCore

jobs:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
  - template: /eng/common/templates/job/onelocbuild.yml
    parameters:
      LclPackageId: 'LCL-JUNO-PROD-SPATMPLATE'
      LclSource: lclFilesFromPackage
      MirrorRepo: spa-templates
